version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - "8080:80"

  gunicorn:
    build: .
    environment:
      - WORKERS=${WORKERS}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
